#------------------------------------------------------------------------------
# makefile for IntegerStackClient.c with macros
#------------------------------------------------------------------------------

FLAGS   = -std=c99 -Wall
SOURCES = IntegerStack.c IntegerStackClient.c
OBJECTS = IntegerStack.o IntegerStackClient.o
HEADERS = IntegerStack.h
EXEBIN  = IntegerStackClient

all: $(EXEBIN)

$(EXEBIN) : $(OBJECTS) $(HEADERS)
	gcc -o $(EXEBIN) $(OBJECTS)

$(OBJECTS) : $(SOURCES) $(HEADERS)
	gcc -c $(FLAGS) $(SOURCES)

clean :
	rm -f $(EXEBIN) $(OBJECTS)

check:
	valgrind --leak-check=full $(EXEBIN) 
